version: '3.6'
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    image: techaid-api:1.0.0
    # name is explicitly defined as the other containers like dashboard depends on this name
    container_name: techaid-server-web-1
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI}
      DATASOURCE_PASSWORD: ${DB_PASS}
      DATASOURCE_URL: ${DB_URL}
      DATASOURCE_USERNAME: ${DB_USER}
      AUTH0_AUDIENCE: ${AUTH0_AUDIENCE}
      AUTH0_DOMAIN: ${AUTH0_DOMAIN}
      AUTH0_CLIENT_ID:
      AUTH0_CLIENT_SECRET:
      JWT_ISSUER: ${JWT_ISSUER}
      GOOGLE_PLACES_KEY:
      GMAIL_CLIENT_ID:
      GMAIL_CLIENT_SECRET:
      GMAIL_REFRESH_TOKEN:
      DDL_AUTO: update
      SHOW_SQL: "${SHOW_SQL:-true}"
      TOKEN_ATTRIBUTE: ${TOKEN_ATTRIBUTE}
      DEV_APP: "https://app-testing.communitytechaid.org.uk/"
      TYPEFORM_KEY: ${TYPEFORM_KEY}
    command: []
    volumes:
      - ./src/main/resources/application-local.yml:/app/config/application-local.yml:ro
      - ./src/main/resources/application.yml:/app/config/application.yml:ro
      - ./src/main/resources/db:/db
      - ./src:/app/src
    depends_on:
      - postgres
    ports:
      - ${PORT:-8080}:8080
#  proxy:
#    image: nginx:1.16-alpine
#    depends_on:
#      - web
#    ports:
#      - 8080:80
#    volumes:
#      - ./docker/proxy.conf:/etc/nginx/nginx.conf
  postgres:
    #using the latest version of postgres
    image: postgres:16
    environment:
      POSTGRES_DB: techaid-api
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    ports:
      - 5423:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    ports:
      - 8900:8080

volumes:
  pgdata: {}

networks:
  # explicitly defining name because dashboard depends on this name to connect to the same network
  default:
    name: techaid-server_default
