#spring:
#  profiles.include: []

auth:
  cors:
    enabled: true
    routes:
      - origin: 'https://app.communitytechaid.org.uk'
        path: '*'
        headers:
          Access-Control-Allow-Methods: 'GET, POST, PUT, PATCH, DELETE, OPTIONS'
          Access-Control-Allow-Headers: '*'
      - origin: 'https://app-testing.communitytechaid.org.uk'
        path: '*'
        headers:
          Access-Control-Allow-Methods: 'GET, POST, PUT, PATCH, DELETE, OPTIONS'
          Access-Control-Allow-Headers: '*'

spring:
  jpa:
    hibernate:
      ddl-auto: none

logging.level:
  cta: DEBUG