apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" . }}-config
data:
  DATASOURCE_URL: "jdbc:postgresql://name: {{ include "app.fullname" . }}-db.svc:5432/{{ .Values.db.name }}"
  {{- with .Values.configData }}
  {{- . | toYaml | nindent 2 }}
  {{- end }}