jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/app

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - restore_cache:
          keys:
            - app-source-{{ .Branch }}-{{ .Revision }}
            - app-source-{{ .Branch }}-
            - app-source-

      - checkout
      - save_cache:
          key: app-source-{{ .Branch }}-{{ .Revision }}
          paths:
            - ~/app

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run: gradle clean build test
      - save_cache:
          key: v1-build-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - build
            - Dockerfile

  push_docker_image:
    working_directory: ~/app
    executor: gcp-gcr/default
    steps:
      - restore_cache:
          key: v1-build-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
      - gcp-gcr/gcr-auth
      - gcp-gcr/build-image:
          image: techaid-dashboard
          registry-url: eu.gcr.io
          tag: prod-${CIRCLE_SHA1:0:7}
      - gcp-gcr/push-image:
          image: techaid-dashboard
          registry-url: eu.gcr.io
          tag: prod-${CIRCLE_SHA1:0:7}
orbs:
  gcp-gcr: circleci/gcp-gcr@0.8.0
version: 2.1
workflows:
  version: 2
  ci_workflow:
    jobs:
      - build
      - push_docker_image:
          context: global
          requires:
            - build
          filters:
            branches:
              only:
                - master