apiVersion: v1
kind: Service
metadata:
  name: stretech-svc
  namespace: apps
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: stretech
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: apps
  name: stretech
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stretech
  template:
    metadata:
      labels:
        app: stretech
    spec:
      imagePullSecrets:
        - name: gcr-regcred
      containers:
        - image: eu.gcr.io/retinue-io/stretech:latest
          name: stretech-web
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 100
            timeoutSeconds: 5
          env:
          envFrom:
            - configMapRef:
                name: stretech-config
            - secretRef:
                name: stretech-db-auth
            - secretRef:
                name: stretech-secret
